### PR TITLE
Add tutorial on how to downscale a Vanilla cluster

### PR DESCRIPTION
**Pull request by marregui**
The tutorial is really my draft for answering

https://community.crate.io/t/from-three-node-cluster-to-single-node/326

so I want it to be self contained and on context. I will likely work on it during the weekend.

I will amend this commit message when/if we merge.

### CODE REVIEW

**Comment by marregui** [comment]
Hi @matthijskrul ,

That is the draft for the tutorial on how to downscale a cluster. 

Best!

**Comment by matthijskrul** [comment]
Approving for now, to be adapted into a tutorial/guide for the Cloud docs subsequently.

Some RST notes:
- top level headings (after the title) with ==== instead of ----
- closed lists with *** instead of ---
- a table of contents and section labels would be handy

**Review by matthijskrul — APPROVED** [review]

**Comment by nomicode** [comment]
thank you for writing this!!

however, our current intention is to keep the "tutorials" section of the docs for content geared more towards new users

for this type of content, I would put it in the guide section (soon to be renamed "how-tos")

if it's not too much trouble, could you recreate this PR on https://github.com/crate/guide?

**Comment by marregui** [comment]
Hey,

Absolutely, will amend the RST syntax, and will PR-migrate.

Thank you for the feedback.

**Comment by marregui** [comment]
superseded by https://github.com/crate/guide/pull/159/

**Pull request closed without merging**
